name: Generate Snake Gif

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Generate snake game
      uses: Platane/snk@v3
      with:
        github_user_name: ${{ github.repository_owner }}
        outputs: |
          dist/magic-snake/github-snake.svg
          dist/magic-snake/github-snake-dark.svg?palette=github-dark
          dist/magic-snake/github-snake.gif?color_snake=purple&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

    - name: Upload Artifacts 
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: main
        build_dir: dist
        keep_history: true
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
